### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by wayneashleyberry** [ryhan/fixie#11]
`fixie()` isn't exposed to the global scope as far I can see,
the documentation is very misleading here...

**Comment by ryhan** [comment]
Working on a fix.

**Comment by ryhan** [comment]
`fixie()` is no longer exposed, in favor of `fixie.init([query]);`

To target a single class, use `fixie.init([".classname"]);`

However, this opens up the opportunity to target several classes and ids.

```
fixie.init(["tagname",".classname", "#id", ... other CSS selectors]);
```
