### ISSUE TITLE
Child elements

### ISSUE THREAD

**Issue by wayneashleyberry** [ryhan/fixie#16]
Aloha!

(loving this little script so so much btw)

I'm having a problem with child elements, take this example

```
<article data-fixie="true">
  <p>Foo</p>
  <p>Bar</p>
</article>
```

Ideally i'd want fixie to place text in the two `<p>` elements, currently fixie will replace the entire contents of the `<article>` element.

The motivation for this is that my templates are becoming incredibly verbose by adding `class="fixie"` or `data-fixie="true"`, where running `fixie('p, img, h1, h2')` is unsafe because that would remove any child elements.

a little example

```
<div id="main">
  <img id="banner" data-fixie="true" width="940" height="200" />
  <div class="col alpha">
    <img data-fixie="true" height="200" width="300" />
    <h2 data-fixie="true"></h2>
    <p data-fixie="true">
  </div>
  <div class="col">
    <img data-fixie="true" height="200" width="300" />
    <h2 data-fixie="true"></h2>
    <p data-fixie="true">
  </div>
  <div class="col omega">
    <img data-fixie="true" height="200" width="300" />
    <h2 data-fixie="true"></h2>
    <p data-fixie="true">
  </div>
  <div class="clearfix"></div>
  <h1 data-fixie="true"></h1>
  <article data-fixie="true">
    <p>Foo
    <p>Bar
  </article>
</div>
```

Thoughts?

**Comment by ryhan** [comment]
Good idea - perhaps if there's content within a tag, fixie will target the child elements?

**Comment by eskimoblood** [comment]
add fix for this issue: https://github.com/rthprog/fixie/pull/18

**Comment by wayneashleyberry** [comment]
Awesome :)

**Comment by ryhan** [comment]
Merged.
