### ISSUE TITLE
Child elements

### ISSUE THREAD

**Issue by wayneashleyberry** [ryhan/fixie#19]
just want to make sure my comments don't get lost

the pull request to fix #16 didn't fix everything

https://github.com/rthprog/fixie/pull/18

**Comment by ryhan** [comment]
Made an update that might address your concerns https://github.com/rthprog/fixie/commit/f5fe164c2c328ad4db508f8e8f3a3faeba40bf22

## Updated Behavior

Child elements are targeted, but content is never overwritten.

## Example

```
<body class="fixie">
<p></p>
<p>Hello, here's a link <a></a>
</body>
```

will cause fixie to add content to the first `<p>` tag, and the `<a>` tag. 

It will not override the "Hello..." text.

Do you think this is the right thing to do?

**Comment by wayneashleyberry** [comment]
Amazing!

thanks@rthprog, issues fixed and not replacing existing content is a great addition :)
