### ISSUE TITLE
Images in Firefox

### ISSUE THREAD

**Issue by wayneashleyberry** [ryhan/fixie#21]
Image sizes aren't being read correctly in Firefox 12 which results in incorrect url's for placehold.it

`<img class="banner" width="960" height="320" />`

comes out as

`<img class="banner" width="17" height="320" src="http://placehold.it/0x17">`

**Comment by ryhan** [comment]
Pulled an update that I suspect might fix the problem. 

`<img class="banner" width="960" height="320" />` was correctly rendered in Firefox 8.

Can you confirm/deny if the most recent update fixes this problem?

**Comment by wayneashleyberry** [comment]
nope, still bust

http://cl.ly/1R1I0v160j2R161k2j0m/o

**Comment by ryhan** [comment]
Installing Firefox 12 asap.

I wonder where the 17 is coming from... any similar problems with other browsers on your system?

**Comment by eskimoblood** [comment]
Works for me in FF12

**Comment by wayneashleyberry** [comment]
@rthprog chrome, opera, safari, safari mobile and the default android browser are all fine :(

just FF

**Comment by eskimoblood** [comment]
maybe some addon???

**Comment by wayneashleyberry** [comment]
ugh. cleared cache, re-installed, disabled everything. images are still broken :(

if it's working fine for you guys i'll carry on hunting on my side

**Comment by ryhan** [comment]
Quick question - does changing `<img class="banner" width="960" height="320" />` to `<img class="banner" width="960px" height="320px" />` fix anything? Just curious.

**Comment by wayneashleyberry** [comment]
nope, doesn't make a difference

**Comment by wayneashleyberry** [comment]
okay, same thing happened on my home computer...

test page here: [https://knnktr.com/test/fixie/](https://knnktr.com/test/fixie/)

source for test page here: [https://github.com/wayneashleyberry/fixie-test](https://github.com/wayneashleyberry/fixie-test)

firefox screenshot: http://cl.ly/1b2q3I1M280i2W3D0k0u

hopefully i'm just having a noob nightmare

**Comment by ryhan** [comment]
Found the bug - caused by usage of `.width` and `.height` instead of `.getAttribute('width')` and `.getAttribute('height')`.

@wayneashleyberry Can you confirm/deny if the current iteration of fixie solves the issue? I was able to reproduce your problem in FF10, and this fix solved it for me.

**Comment by wayneashleyberry** [comment]
hurrah!!

thanks @rthprog :)
