### ISSUE TITLE
Image services shows insecure content warning over https

### ISSUE THREAD

**Issue by gagandeep** [ryhan/fixie#29]
Images shows insecure content warning on my chrome over secure connection. 

It is because Image services like placehold.it and placekitten.com don't support https requests.

**Comment by ryhan** [comment]
It's possible to link to an image service (or your own server) that supports https using `fixie.setImagePlaceholder()`.

Here's a sample call from `sample.html`

```
fixie.setImagePlaceholder('http://flickholdr.com/${w}/${h}/fixie').init();
```

Here are some other solutions
- specify an src on the image. Fixie will not overwrite this (recently fixed).
- Set imagePlaceholder to " ". Example: `fixie.setImagePlaceholder(' ').init();`

Are these acceptable solutions to your problem?

**Comment by gagandeep** [comment]
I think, first one will work for me. 

``` javascript
fixie.setImagePlaceholder('http://flickholdr.com/${w}/${h}/fixie').init();
```

Thanks.
