### ISSUE TITLE
Need to allow for dynamic HTML

### ISSUE THREAD

**Issue by thomasdavis** [ryhan/fixie#37]
Planning on using fixie for a large opensource project I'm releasing, need to be able to run fixie or it can pick up elements on the fly.

Also is this the best place to discuss other content types?

**Comment by thomasdavis** [comment]
my bad ignore the request fixie.init(':empty'), but on the second question?

**Comment by ryhan** [comment]
Yep - though I'd recommend making another issue. What did you have in mind?

**Comment by ryhan** [comment]
Also, I'm closing this issue as "Need to allow for dynamic HTML" is resolved.
