### ISSUE TITLE
function call alternative to class api

### ISSUE THREAD

**Issue by stephenhandley** [ryhan/fixie#5]
maybe an alternative / additional api would be to allow for something like

```
fixie.init([".array", "#of .selectors", ".that", ".should", "#be .populated .with .lorem"])
```

or just a string like

```
fixie.init(".string, #of .comma .separated .selectors, .that, .should, #be .populated .with .lorem")
```

I think that would address the class proliferation issue and still be explicit about which dom nodes should be populated. easier to maintain / comment out.

**Comment by ryhan** [comment]
Nice idea!

**Comment by wayneashleyberry** [comment]
Yeah, a more flexible api would be awesome.

I'd specifically like to be able to enable fixie on everything in my `<body>` tag, or just on specific elements.

**Comment by ryhan** [comment]
Fully implemented.

**Comment by stephenhandley** [comment]
awesome! thanks!
